DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    TELEFONE VARCHAR(12),
    DESCRICAO TEXT,
    PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS AGENDA;
CREATE TABLE AGENDA(
    ID INTEGER, 
    USUARIO_ID INTEGER,
    DESCRICAO TEXT,
    TITULO VARCHAR(150),
    DATA TIMESTAMP,
    PRIMARY KEY(ID),
    FOREIGN KEY(USUARIO_ID)
        REFERENCES USUARIO(ID)
)